---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-agent-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-agent
subjects:
- kind: ServiceAccount
  name: my-serviceaccount
  namespace: dev
roleRef:
  kind: ClusterRole
  name: my-agent-role
  apiGroup: rbac.authorization.k8s.io

