---
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: my-pod
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: my-app
    image: python:latest
    command: [ "sleep" ]
    args: [ "infinity" ]