apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    app: mc
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80    
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: container-2
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done

---

apiVersion: v1
kind: Service
metadata:
  name: mc-src
spec:
  selector:
    app: mc
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer