apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-staging
  namespace: demo-app
spec:
  secretName: app-staging-certificate
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - example.com