apiVersion: v1
kind: Pod
metadata:
  name: mypod-01
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c", "echo $(DATA_VALUE) > $(DATA_PATH); sleep 3600"]
    env:
    - name: DATA_VALUE
      valueFrom:
        configMapKeyRef:
          name: nginx-cm
          key: value
          optional: true
    - name: DATA_PATH
      valueFrom:
        configMapKeyRef:
          name: nginx-cm
          key: path
          optional: true
