apiVersion: v1
kind: Pod
metadata:
  name: mypod-03
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /tmp/config
  volumes:
    - name: config-volume
      configMap:
        name: file-cm