apiVersion: v1
kind: Pod
metadata:
  name: mypod-04
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /tmp/config.yaml
      subPath: config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: file-cm