apiVersion: v1
kind: Pod
metadata:
  name: mypod-02
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["/bin/sh", "-c", "echo $value"]
    envFrom:
    - configMapRef:
        name: nginx-cm